name: Dataset Update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Generate new data
        run: |
          python scripts/Denmark-crawler.py
          python scripts/Hungary-crawler.py
          python scripts/Slovakia-crawler.py
          python scripts/Bulgaria-crawler.py
          python scripts/India-crawler.py
          python scripts/Kazakhstan-crawler.py
          python scripts/NewZealand-crawler.py
          python scripts/Jamaica-crawler.py
          python scripts/Bolivia-crawler.py
          python scripts/Myanmar-crawler.py
          python scripts/Panama-crawler.py
          python scripts/Thailand-crawler.py
      - name: Commit data files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit -m "Dataset Update" || echo "Nothing to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: leontian36/covid19-csv
          github_token: ${{ secrets.GITHUB_TOKEN }}
